name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'Oracle'

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test
