name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt-hotspot'

    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        cli: 'latest'

    - name: Check out action
      uses: actions/checkout@v4
      with:
        path: '.'

    - name: Build action 1
      run:  lein install

    - name: Build action 2
      run: lein codox

    - name: Install dependencies
      run: lein deps

    - name: Compile tests
      run: lein do with-profiles java-tests-compile uberjar, test, install, codox

    - name: Run tests
      run: lein test

    - name: Install action
      run: lein install
